### ISSUE TITLE
Wilderness residence – disallowing placing furniture

### ISSUE THREAD

**Issue by bobhenl** [Ste3et/ProtectionLib#5]
Hi, I want to ask for feature / report a bug (not sure what is this) about placing furniture in wilderness, where players don't have permissions to build and destroy. In residence flags.yml file I have this option:
```
    world:
      use: true
      build: false
      ignite: true
      firespread: false
      damage: true
      creeper: true
      tnt: true
      pvp: true
      destroy: false
      tp: true
```
Which means that players can't place and destroy in wilderness until they create their own residence. BUT NOW the problem is when you have furniture and you CAN place it whatever you want.... Players normally have permission to place furniture here (checked via "/protectionlib debug <player>"). But in other players residences it's ok, they can't place it there, there's just problem with this.
